#!/bin/bash

export AWS_REGION="us-east-1"
export AWS_ACCESS_KEY_ID="123456789"
export AWS_SECRET_ACCESS_KEY="supersecret"
SCRIPTDIR=$(cd $(dirname $0) && pwd)
BASEDIR=$(cd $SCRIPTDIR/.. && pwd)
LAMBDADIR=$(cd "$BASEDIR/../../node_modules/lambda-local/bin/" && pwd)
EVENT_NUMBER=${1:-5}
EVENT_FILE="${BASEDIR}/events/put_event.js"
EVENT_CODE="${BASEDIR}/code/PutEvents.js"

> event.log
for i in $(seq 1 ${EVENT_NUMBER}) ; do
  "${LAMBDADIR}/lambda-local" -l "$EVENT_CODE" -e "$EVENT_FILE"  >> event.log
done
if [ "$(cat event.log | grep -c "Error while inserting data")" -gt 0 ] ; then
  echo "[ERROR] Errors while sending events:"
  cat event.log
  exit 1
fi

echo "Finished sending ${EVENT_NUMBER} events"
