#!/bin/bash
export AWS_REGION="us-east-1"
export AWS_ACCESS_KEY_ID="123456789"
export AWS_SECRET_ACCESS_KEY="supersecret"
SCRIPTDIR=$(cd $(dirname $0) && pwd)
BASEDIR=$(cd $SCRIPTDIR/.. && pwd)
LAMBDADIR=$(cd "$BASEDIR/../../node_modules/lambda-local/bin/" && pwd)
EVENT_FILE="${BASEDIR}/events/request_events.js"
EVENT_CODE="${BASEDIR}/code/request_events.js"
EVENT_LOG_FILE="events.log"

"$LAMBDADIR/lambda-local" -l "$EVENT_CODE" -e "$EVENT_FILE" >  "${EVENT_LOG_FILE}"
N_MESSAGES=$(grep -o 'Count: [0-9]\+' ${EVENT_LOG_FILE} | awk '{print $2}')
echo "Read '${N_MESSAGES}' messages"
